# Generated by Django 5.0.6 on 2024-05-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_address_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmpassword',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
