# Generated by Django 5.0.6 on 2024-05-21 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_email_customer_img_customer_priority_and_more'),
        ('order', '0002_remove_order_created_remove_order_updated_and_more'),
        ('product', '0003_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
                ('total_price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_cart', to='product.product')),
            ],
        ),
    ]
