# Generated by Django 5.0.6 on 2024-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cart Stage'), (1, 'Order Stage'), (2, 'Order Confirmed'), (3, 'Order Processed'), (4, 'Order Delivered'), (5, 'Order Rejected')], default=0),
        ),
    ]
